### ISSUE TITLE
How can I read from the realtime database as a list? - add *ngFor support

### ISSUE THREAD

**Issue by Gorniv** [hamedbaatour/angularfire-lite#7]
Hello, how i can write like this:
`this.items = db.list('news', ref => ref.orderByChild('time').limitToFirst(25)).valueChanges();` ?

**Comment by hamedbaatour** [comment]
@Gorniv Thank you for posting the very issue here and it is a good one.

AngularFire Lite does not complicate things so when you want to read data from the realtime database you have to remember only one function that you are going to use 99% of the time which is the read function which you should pass it the reference to the database.

the functions returns the actual data when you give it the absolute path to the data (example: string)
```
    this.database = this.db.read('hellolist/hellodata');
    this.database.subscribe((data) => {
      console.log(data); // console logs the string stored in the database
      this.databaseData = data;
    });
```
and returns an object when you give it the absolute path to a data list.


```
    this.database = this.db.read('hellolist');
    this.database.subscribe((data) => {
      console.log(data); // console logs an object containing hellodata and other key value pairs
      this.databaseData = data;
    });
```

everything works if you simply want to use that data but as it is but as you know the ngFor does not support looping over objects so this is a great reminder to add support for ngFor which will be fixed in the next very few days. So thank you for posting this issue as this helps improving the library

**Comment by hamedbaatour** [comment]
@Gorniv Thank you for posting the very issue here and it is a good one.

AngularFire Lite does not complicate things so when you want to read data from the realtime database you have to remember only one function that you are going to use 99% of the time which is the read function which you should pass it the reference to the database.

the functions returns the actual data when you give it the absolute path to the data (example: string)
```
    this.database = this.db.read('hellolist/hellodata');
    this.database.subscribe((data) => {
      console.log(data); // console logs the string stored in the database
      this.databaseData = data;
    });
```
and returns an object when you give it the absolute path to a data list.


```
    this.database = this.db.read('hellolist');
    this.database.subscribe((data) => {
      console.log(data); // console logs an object containing hellodata and other key value pairs
      this.databaseData = data;
    });
```

everything works if you simply want to use that data but as it is but as you know the ngFor does not support looping over objects so this is a great reminder to add support for ngFor which will be fixed in the next very few days. So thank you for posting this issue as this helps to improve the library

**Comment by hamedbaatour** [comment]
@Gorniv Fixed it! 🎉 
now you can use the `*ngFor` directive with `async` pipe if you pass a path pointing to a list in your real-time database to the read function. so now you can do the following to iterate over a list:

**1. Inject the AngularFire Lite database service:**
`  constructor(public db: AngularFireLiteDatabase) {}`

**2. reference the list of data in your real-time database by passing its path to the read function**
`this.items = this.db.read('news');`

**3. then you iterate over all the data and print it in your template like this:**
```
<ul>
  <li *ngFor="let item of items | async">{{item}}</li>
</ul>
```
extremely simple syntax! for maximum productivity isn't that beautiful to use one function to get a list of data or a single item. this feature was also added to the other database listeners which can use them just like the read funciton and they are :
 `childAdded(ref)` , `childChanged(ref)` , `childRemoved(ref)` and `childMoved(ref)` 😃 

again thank you for posting this issue and if you have any feature request please open a new issue and I will try my best to add it in few days or in few hours if that is possible.
